version: '2'
volumes:
  database_data:
    driver: local
networks:
  default:
    driver: bridge
  external:
    external:
      name: rnet
services:
  itag:
    image: jjrom/itag-nginx:5
    restart: always
    build:
      context: ./
      dockerfile: ./build/nginx/Dockerfile
    depends_on:
      - phpfpm
      - itagdb
    networks:
      - external
      - default
    ports:
      - ${ITAG_EXPOSED_PORT}:8080
  phpfpm:
    image: jjrom/itag-fpm:5
    restart: always
    build:
      context: ./
      dockerfile: ./build/phpfpm/Dockerfile
    networks:
      - default
    volumes:
      - .run/config.php:/conf/config.php:ro
  itagdb:
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=${ITAG_DATABASE_USER_NAME}
      - POSTGRES_PASSWORD=${ITAG_DATABASE_USER_PASSWORD}
      - POSTGRES_DB=${ITAG_DATABASE_NAME}
    ports:
      - ${ITAG_DATABASE_EXPOSED_PORT}:5432
    networks:
      - default
    volumes:
      - database_data:/var/lib/postgresql/data
