version: '2'
volumes:
  database_data:
    driver: local
networks:
  default:
    driver: bridge
  external:
    external:
      name: rnet
services:
  itag:
    image: jjrom/itag:5.0
    restart: always
    build:
      context: ./
      dockerfile: ./build/itag/Dockerfile
    depends_on:
      - itagdb
    networks:
      - external
      - default
    ports:
      - ${ITAG_EXPOSED_PORT}:80
    volumes:
      - ./app:/app:ro
      - .run/config.php:/conf/config.php:ro
      - .run/php.ini:/usr/local/etc/php/php.ini:ro
  itagdb:
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=${ITAG_DATABASE_USER_NAME}
      - POSTGRES_PASSWORD=${ITAG_DATABASE_USER_PASSWORD}
      - POSTGRES_DB=${ITAG_DATABASE_NAME}
    ports:
      - ${ITAG_DATABASE_EXPOSED_PORT}:5432
    networks:
      - default
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
